### ISSUE TITLE
Fix the 404s

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source-Legacy#16]
https://docs.google.com/spreadsheets/d/163ByWW9uOTyFdxFcxAMDH25vWOm5ySyfc54GEKv8c4Y/edit#gid=0 lists pages that have links giving 404 errors. Need to update and put in the correct links.

**Comment by billy-the-fish** [comment]
3.x links are listed on the top of: https://docs.google.com/spreadsheets/d/16ecF-qNGIpsZBIhAtGbwFQeVABbw7zGF0zj49k1QOUo/edit#gid=0

**Comment by billy-the-fish** [comment]
Just done a link check using your fix branch. The following are left:


- On source page path = /en/3.x/interactive-live-streaming/advanced-features/custom-audio:
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-audio-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-audio-streaming)

- On source page path = /en/3.x/interactive-live-streaming/advanced-features/media-push:
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-video-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-video-streaming)
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-audio-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-audio-streaming)

- On source page path = /en/3.x/interactive-live-streaming/advanced-features/raw-video-data:
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-video-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/interactive-live-streaming/best-practices/reduce-app-size:
  -> linking to ../../../video-calling/basic-features/screensharing?platform=iOS (resolved as: /en/video-calling/basic-features/screensharing)

- On source page path = /en/3.x/interactive-live-streaming/introduction/pricing:
  -> linking to /en/interactive-whiteboard/reference/billing-policies

- On source page path = /en/3.x/interactive-live-streaming/introduction/release-notes:
  -> linking to ../../../interactive-live-streaming/advanced-features/media-push#prerequisites (resolved as: /en/interactive-live-streaming/advanced-features/media-push)
  -> linking to ../../../interactive-live-streaming/advanced-features/multiple-channel (resolved as: /en/interactive-live-streaming/advanced-features/multiple-channel)
  -> linking to ../../../interactive-live-streaming/advanced-features/media-relay (resolved as: /en/interactive-live-streaming/advanced-features/media-relay)

- On source page path = /en/3.x/interactive-live-streaming/introduction/service-sunset-plans:
  -> linking to ../../../interactive-live-streaming/advanced-features/media-push (resolved as: /en/interactive-live-streaming/advanced-features/media-push)
  -> linking to /en/media-push/reference/restful-api

- On source page path = /en/3.x/interactive-live-streaming/reference/channel-management-rest-api:
  -> linking to ../reference/restful-authentication (resolved as: /en/3.x/interactive-live-streaming/reference/restful-authentication)
  -> linking to ../agora-console-rest-api#get-all-projects (resolved as: /en/3.x/interactive-live-streaming/agora-console-rest-api)

- On source page path = /en/3.x/interactive-live-streaming/reference/manage-agora-account:
  -> linking to ../../agora-analytics/overview/product-overview (resolved as: /en/3.x/agora-analytics/overview/product-overview)
  -> linking to ../../extensions-marketplace/overview/product-overview (resolved as: /en/3.x/extensions-marketplace/overview/product-overview)

- On source page path = /en/3.x/interactive-live-streaming/reference/mpk-release:
  -> linking to ../../../interactive-live-streaming/advanced-features/mediaplayer-kit#function-description (resolved as: /en/interactive-live-streaming/advanced-features/mediaplayer-kit)
  -> linking to ../../../interactive-live-streaming/advanced-features/mediaplayer-kit#integrate-the-mediaplayer-kit (resolved as: /en/interactive-live-streaming/advanced-features/mediaplayer-kit)

- On source page path = /en/3.x/interactive-live-streaming/reference/security:
  -> linking to ../../video-calling/develop/authentication-workflow (resolved as: /en/3.x/video-calling/develop/authentication-workflow)
  -> linking to ../../video-calling/develop/media-stream-encryption (resolved as: /en/3.x/video-calling/develop/media-stream-encryption)
  -> linking to ../../video-calling/develop/authentication-workflow#create-and-run-a-token-server (resolved as: /en/3.x/video-calling/develop/authentication-workflow)

- On source page path = /en/3.x/video-calling/advanced-features/custom-audio:
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-audio-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-audio-streaming)

- On source page path = /en/3.x/video-calling/advanced-features/custom-video:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/video-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/video-calling/advanced-features/raw-video-data:
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-video-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/video-calling/basic-features/adjust-volume:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/video-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/video-calling/basic-features/audio-profiles:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/video-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/video-calling/basic-features/lastmile-quality:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/video-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/video-calling/basic-features/screensharing:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/video-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/video-calling/best-practices/reduce-app-size:
  -> linking to ../../../video-calling/basic-features/screensharing?platform=iOS (resolved as: /en/video-calling/basic-features/screensharing)

- On source page path = /en/3.x/video-calling/introduction/pricing:
  -> linking to /en/interactive-whiteboard/reference/billing-policies

- On source page path = /en/3.x/video-calling/introduction/release-notes:
  -> linking to ../advanced-features/media-push (resolved as: /en/3.x/video-calling/advanced-features/media-push)
  -> linking to ../../../interactive-live-streaming/advanced-features/media-push#prerequisites (resolved as: /en/interactive-live-streaming/advanced-features/media-push)
  -> linking to ../../../interactive-live-streaming/advanced-features/multiple-channel (resolved as: /en/interactive-live-streaming/advanced-features/multiple-channel)
  -> linking to ../../../interactive-live-streaming/advanced-features/media-relay (resolved as: /en/interactive-live-streaming/advanced-features/media-relay)

- On source page path = /en/3.x/video-calling/introduction/service-sunset-plans:
  -> linking to ../../../interactive-live-streaming/advanced-features/media-push (resolved as: /en/interactive-live-streaming/advanced-features/media-push)
  -> linking to /en/media-push/reference/restful-api

- On source page path = /en/3.x/video-calling/reference/channel-management-rest-api:
  -> linking to ../reference/restful-authentication (resolved as: /en/3.x/video-calling/reference/restful-authentication)
  -> linking to ../agora-console-rest-api#get-all-projects (resolved as: /en/3.x/video-calling/agora-console-rest-api)

- On source page path = /en/3.x/video-calling/reference/manage-agora-account:
  -> linking to ../../agora-analytics/overview/product-overview (resolved as: /en/3.x/agora-analytics/overview/product-overview)
  -> linking to ../../extensions-marketplace/overview/product-overview (resolved as: /en/3.x/extensions-marketplace/overview/product-overview)

- On source page path = /en/3.x/video-calling/reference/mpk-release:
  -> linking to ../../../interactive-live-streaming/advanced-features/mediaplayer-kit#function-description (resolved as: /en/interactive-live-streaming/advanced-features/mediaplayer-kit)
  -> linking to ../../../interactive-live-streaming/advanced-features/mediaplayer-kit#integrate-the-mediaplayer-kit (resolved as: /en/interactive-live-streaming/advanced-features/mediaplayer-kit)

- On source page path = /en/3.x/video-calling/reference/security:
  -> linking to ../../video-calling/develop/authentication-workflow (resolved as: /en/3.x/video-calling/develop/authentication-workflow)
  -> linking to ../../video-calling/develop/media-stream-encryption (resolved as: /en/3.x/video-calling/develop/media-stream-encryption)
  -> linking to ../../video-calling/develop/authentication-workflow#create-and-run-a-token-server (resolved as: /en/3.x/video-calling/develop/authentication-workflow)

- On source page path = /en/3.x/voice-calling/advanced-features/custom-audio:
  -> linking to ../../../interactive-live-streaming/quickstart-guide/start-audio-streaming (resolved as: /en/interactive-live-streaming/quickstart-guide/start-audio-streaming)

- On source page path = /en/3.x/voice-calling/basic-features/adjust-volume:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/voice-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/voice-calling/basic-features/audio-profiles:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/voice-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/voice-calling/basic-features/lastmile-quality:
  -> linking to ../quickstart-guide/start-video-streaming (resolved as: /en/3.x/voice-calling/quickstart-guide/start-video-streaming)

- On source page path = /en/3.x/voice-calling/best-practices/reduce-app-size:
  -> linking to ../../../video-calling/basic-features/screensharing?platform=iOS (resolved as: /en/video-calling/basic-features/screensharing)

- On source page path = /en/3.x/voice-calling/introduction/pricing:
  -> linking to /en/interactive-whiteboard/reference/billing-policies

- On source page path = /en/3.x/voice-calling/introduction/release-notes:
  -> linking to cdn_streaming_android (resolved as: /en/3.x/voice-calling/introduction/cdn_streaming_android)
  -> linking to media_relay_android (resolved as: /en/3.x/voice-calling/introduction/media_relay_android)
  -> linking to voice_effect_android (resolved as: /en/3.x/voice-calling/introduction/voice_effect_android)

- On source page path = /en/3.x/voice-calling/introduction/service-sunset-plans:
  -> linking to ../../../interactive-live-streaming/advanced-features/media-push (resolved as: /en/interactive-live-streaming/advanced-features/media-push)
  -> linking to /en/media-push/reference/restful-api

- On source page path = /en/3.x/voice-calling/reference/channel-management-rest-api:
  -> linking to ../reference/restful-authentication (resolved as: /en/3.x/voice-calling/reference/restful-authentication)
  -> linking to ../agora-console-rest-api#get-all-projects (resolved as: /en/3.x/voice-calling/agora-console-rest-api)

- On source page path = /en/3.x/voice-calling/reference/manage-agora-account:
  -> linking to ../../agora-analytics/overview/product-overview (resolved as: /en/3.x/agora-analytics/overview/product-overview)
  -> linking to ../../extensions-marketplace/overview/product-overview (resolved as: /en/3.x/extensions-marketplace/overview/product-overview)

- On source page path = /en/3.x/voice-calling/reference/security:
  -> linking to ../../video-calling/develop/authentication-workflow (resolved as: /en/3.x/video-calling/develop/authentication-workflow)
  -> linking to ../../video-calling/develop/media-stream-encryption (resolved as: /en/3.x/video-calling/develop/media-stream-encryption)
  -> linking to ../../video-calling/develop/authentication-workflow#create-and-run-a-token-server (resolved as: /en/3.x/video-calling/develop/authentication-workflow)

**Comment by Kishan-Dhakan** [comment]
[This](https://github.com/AgoraIO/Docs-Source-Legacy/issues/16#issuecomment-1268483958) is fixed with https://github.com/AgoraIO/Docs-Source/pull/582, https://github.com/AgoraIO/Docs-Source-Legacy/pull/18, https://github.com/AgoraIO/Docs-Source-Legacy/pull/17 and https://github.com/AgoraIO/Docs-Source/pull/572
